# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          yarn install --frozen-lockfile
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests
        run: yarn cypress:run
        continue-on-error: true
        
      - name: Merge test reports
        run: yarn combine:report

      - name: Generate HTML report
        run: yarn generate:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
